framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

            # https://packagist.org/packages/koco/messenger-kafka
            kafka_async:
                serializer: App\Infrastructure\BrokerMessages\Kafka\Serializer
                dsn: '%env(KAFKA_DSN)%'
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: 'events'

        default_bus: command.bus

        buses:
            # CQRS
            command.bus: ~
            query.bus: ~

            # Broker Messages
            event.bus: ~

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
